name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: testSwordPrivate
      id: testswordprivate
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testSwordPrivate
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "SwordTest.testPrivate"
        timeout: 10
        max-score: 1
    - name: testSwordSetter
      id: testswordsetter
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testSwordSetter
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "SwordTest.testSetter"
        timeout: 10
        max-score: 2
    - name: testSwordSetter2
      id: testswordsetter2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testSwordSetter2
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "SwordTest.testSetter2"
        timeout: 10
        max-score: 2
    - name: testSwordSetter3
      id: testswordsetter3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testSwordSetter3
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "SwordTest.testSetter3"
        timeout: 10
        max-score: 2
    - name: testSwordGetter
      id: testswordgetter
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testSwordGetter
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "SwordTest.testGetter"
        timeout: 10
        max-score: 1
    - name: testHeroPrivate
      id: testheroprivate
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testHeroPrivate
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testPrivate"
        timeout: 10
        max-score: 1
    - name: testHeroSetter
      id: testherosetter
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testHeroSetter
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testSetter"
        timeout: 10
        max-score: 2
    - name: testHeroGetter
      id: testherogetter
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testHeroGetter
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testGetter"
        timeout: 10
        max-score: 1
    - name: testMain
      id: testmain
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testMain
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "ProgB2Test.testMain"
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTSWORDPRIVATE_RESULTS: "${{steps.testswordprivate.outputs.result}}"
        TESTSWORDSETTER_RESULTS: "${{steps.testswordsetter.outputs.result}}"
        TESTSWORDSETTER2_RESULTS: "${{steps.testswordsetter2.outputs.result}}"
        TESTSWORDSETTER3_RESULTS: "${{steps.testswordsetter3.outputs.result}}"
        TESTSWORDGETTER_RESULTS: "${{steps.testswordgetter.outputs.result}}"
        TESTHEROPRIVATE_RESULTS: "${{steps.testheroprivate.outputs.result}}"
        TESTHEROSETTER_RESULTS: "${{steps.testherosetter.outputs.result}}"
        TESTHEROGETTER_RESULTS: "${{steps.testherogetter.outputs.result}}"
        TESTMAIN_RESULTS: "${{steps.testmain.outputs.result}}"
      with:
        runners: testswordprivate,testswordsetter,testswordsetter2,testswordsetter3,testswordgetter,testheroprivate,testherosetter,testherogetter,testmain
